export enum JobStatus {
  NEW = 'NEW',
  USER_APPROVED = 'USER_APPROVED',
  USER_REJECTED = 'USER_REJECTED',
  AI_DONE = 'AI_DONE',
  SENT = 'SENT',
  REPLIED = 'REPLIED',
  REJECTED = 'REJECTED',
  JOB_APPLYED = 'JOB_APPLYED',
}
